### PR TITLE
patched up the insert bugs

### PR DESCRIPTION
**Pull request by jjhesk**
patched up the bugs on insert. Please also issue an new gradle for dev. Thanks.

### CODE REVIEW

**Comment by cymcsg** [comment]
Do you mean that update gradle version from 2.2.1 to 2.6?

**Comment by jjhesk** [comment]
I meant by the new compilable dependency in gradle. @cymcsg  thanks

**Comment by cymcsg** [comment]
I have released 0.3.16 for the latest version.

**Comment by jjhesk** [comment]
@cymcsg appreciate your in time support.. trying to rush thru me deadline..

**Pull request merged**
