### PR TITLE
HKM update from admobs fixes

### PR DESCRIPTION
**Pull request by jjhesk**
fixes are listed. Reference check  #66
- [x] better implementations
- [x] fixed touch position from selection item on the list
- [x] admob enhancement
- [x] add items
- [x] add helper implementation for listFragment using admob or list recycleview

### CODE REVIEW

**Comment by cymcsg** [comment]
Thank you very much.But this PR also contains previous commits which I have merged.I do not think it's a good idea which merges with useless commits.

**Comment by jjhesk** [comment]
u want me to update ur code then i add my merge?

**Comment by cymcsg** [comment]
It's very kind of you to do that.Or maybe you can rebase to remove the commits which have been merged.

**Comment by jjhesk** [comment]
o. i will need to find some time to do it. until then just dont merge my code or update your code from mine because u want me to do it. thx

**Pull request closed without merging**
