### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by jjhesk**
```java

/**
     * This is the enhanced listview injection model that will be able to work with Googlge Admob, DoubleClick, and
     * related custom cell injection on the fly. It provides two specific options for the view to be taken place.
     * While insertOnce=true will increase the performance and false will slow down a little bit on the performance but it is insignificant.
     *
     * @param adview      The AD mob view
     * @param insertOnce  only insert once and hold into the adapter object, that means the ad will only shown once in the list view
     * @param setInterval the order of item to show the ad. if @insertOnce=false the ad will show on interval bases.
     * @param L           the data source
     */
    public AdmobAdapter(Adv adview, boolean insertOnce, int setInterval, List<T> L) {
        this(adview, insertOnce, setInterval, L, null);
    }

```
I just did it.

### CODE REVIEW

**Comment by jjhesk** [comment]
please check out this working admob specific adapter. 
[call](https://github.com/cymcsg/UltimateRecyclerView/pull/43)

**Comment by jjhesk** [comment]
ci failed i think its because of the generic types or some comments.

**Comment by cymcsg** [comment]
Thank you!
I have merged the PR into the dev branch.
I am hoping for your more contribution to the project.

**Comment by cymcsg** [comment]
However,when I tried the  the loadmore or swipe to fresh feature in TestAbMob,there is nothing happen.So I wonder is there something wrong with those features?

**Comment by jjhesk** [comment]
yes, i still need some more time to put the code on these functions.  Current I will need this for my project. Are there any snapshot or maven that i can call to put into the my compile list?

**Comment by cymcsg** [comment]
OK.I think you can try ``  compile 'com.marshalchen.ultimaterecyclerview:library:0.3.3'`` to use the latest version.

**Comment by jjhesk** [comment]
Thank you. Its a good team work. I will come back to add more on the things I left from the todo list soon. But still if u got time to fill out the blank just do it and let me know with the new version. By the way, I think you might need to update the README for better documents and sample code specific on adview implementations.

**Comment by jjhesk** [comment]
added new helper

**Comment by jjhesk** [comment]
@cymcsg  update from the fix bug from touch position offset. From using Admob adapter.

**Comment by cymcsg** [comment]
Thank you. Do you mean that I have not merge the commit ``fix bug from touch position offset	97071aa``?

**Comment by jjhesk** [comment]
ok. how do i do so?

**Pull request closed without merging**
