### PR TITLE
Glide and support library versions updated

### PR DESCRIPTION
**Pull request by Yellu**

### CODE REVIEW

**Comment by cymcsg** [comment]
Thank you @Yellu . Could you PR into dev branch instead of master?

**Comment by Yellu** [comment]
Thank you @cymcsg, updated PR to dev.

**Comment by cymcsg** [comment]
Thanks. If you have some free time, could you help fix the problem in travis-ci which alert this PR check error?

**Comment by Yellu** [comment]
Sure, I will try it.

**Pull request merged**
