### PR TITLE
added quick adapter from the base adapter.

### PR DESCRIPTION
**Pull request by jjhesk**
- [x] quick adapter extends from BaseAdapter is completed
- [x] it is still outstanding for the integration from extending the
URA.

### CODE REVIEW

**Comment by jjhesk** [comment]
mentioned from the #135. this will be continuously working to make it more effective in the future. still it has alot of works to do for extend form the utimateadapter. one thing i am looking at is that the typeview support feature is actually overlapping the existing mult type support built in the library. For more simple ideas please refer to [here](https://github.com/hongyangAndroid/base-adapter-helper)

**Comment by cymcsg** [comment]
Awesome work!
I think it's a good idea if you can add some demo or usage to help someone for easily using the quick adapter.
I concern about adding picasso will increase the size of the library in a way.Do you think it is necessary to  use some other method instead of picasso to limit the size?

**Comment by jjhesk** [comment]
If I will have to remove Picasso from the lib then the quick adapter will lose the capabilities to display images in the efficiently.

**Comment by jjhesk** [comment]
```java

+    /**
+     * Will download an image from a URL and put it in an ImageView.<br/>
+     * It uses Square's Picasso library to download the image asynchronously and
+     * put the result into the ImageView.<br/>
+     * Picasso manages recycling of views in a ListView.<br/>
+     * If you need more control over the Picasso settings, use
+     * {BaseAdapterHelper#setImageBuilder}.
+     *
+     * @param viewId   The view id.
+     * @param imageUrl The image URL.
+     * @return The BaseAdapterHelper for chaining.
+     */
+    public BaseAdapterHelper setImageUrl(int viewId, String imageUrl) {
+        ImageView view = retrieveView(viewId);
+        Picasso.with(context).load(imageUrl).into(view);
+        return this;
+    }
+
+    /**
+     * Will download an image from a URL and put it in an ImageView.<br/>
+     *
+     * @param viewId         The view id.
+     * @param requestBuilder The Picasso request builder. (e.g.
+     *                       Picasso.with(context).load(imageUrl))
+     * @return The BaseAdapterHelper for chaining.
+     */
+    public BaseAdapterHelper setImageBuilder(int viewId,
+                                             RequestCreator requestBuilder) {
+        ImageView view = retrieveView(viewId);
+        requestBuilder.into(view);
+        return this;
+    }
+

```

**Comment by Rainer-Lang** [comment]
Why Picasso and not Glide?

**Comment by jjhesk** [comment]
@Rainer-Lang because i have not heard of it before and I have only using Picasso all along my life. haha. whats the good thing about Glide?

**Comment by Rainer-Lang** [comment]
@jjhesk Here are some useful links:
http://inthecheesefactory.com/blog/get-to-know-glide-recommended-by-google/en
https://github.com/bumptech/glide

**Comment by jjhesk** [comment]
@Rainer-Lang  it sounds promising from what they claimed. It seems like a rally between the two groups.  Should I try glide then?

**Comment by Rainer-Lang** [comment]
You should have a look. The syntax is nearly the same. You could test Glide.

**Comment by jjhesk** [comment]
@Rainer-Lang  @cymcsg  check it out with the new features.

**Comment by cymcsg** [comment]
Great! I have merged it into dev branch.

**Pull request closed without merging**
