### PR TITLE
Yellu

### PR DESCRIPTION
**Pull request by Yellu**

### CODE REVIEW

**Comment by Yellu** [comment]
Hi, When can I see the expected changes?

**Comment by cymcsg** [comment]
@Yellu  What would you want to see? Using gradle to get the latest aar or something else?

**Comment by Yellu** [comment]
Hi, Will the changes reflected in the Gradle dependency or do I need to
make any extra changes in Gradle changes??

**Comment by cymcsg** [comment]
You can download the latest version via  ``compile 'com.marshalchen.ultimaterecyclerview:library:0.7.5``

**Comment by Yellu** [comment]
Hi @cymcsg,

Please help me, I am not able to add a header to
UltimateDifferentTypeAdapter.

I tried both the ways by setting NormalHeader and ParallaxHeader, nothing
visible.

**Pull request merged**
