### PR TITLE
Dev merge from the master

### PR DESCRIPTION
**Pull request by jjhesk**
I just developed and tested with the ad banned injection from admob. admob is actually implemented in example app not in the library. This will take care of the situation raised from #39 , #35. Temp fix. #41 discussion also. [work report](https://github.com/101medialab/Hypebeast-Android/issues/3)

### CODE REVIEW

**Comment by cymcsg** [comment]
Thank you very much for the pull request.
However,in my opinion, an adapter support different types of  layout is a common demand while support admob is only a specific demand.The latest version of UltimateRecyclerview supports different types of layout in an adapter. So I do not think it is a good idea to change the UltimateViewAdapter because it is a core class when someone uses UltimateRecyclerview. Maybe it is a better idea to create a new class which extends UltimateViewAdapter or an interface which achieves the admob demand.

**Comment by jjhesk** [comment]
@cymcsg as of the latest pull, there were only a few types supported.

```java
protected class VIEW_TYPES {
        public static final int NORMAL = 0;
        public static final int HEADER = 1;
        public static final int FOOTER = 2;
        public static final int CHANGED_FOOTER = 3;
    }
```
I just added a new type on the views as 
```java
protected class VIEW_TYPES {
        public static final int NORMAL = 0;
        public static final int HEADER = 1;
        public static final int FOOTER = 2;
        public static final int CHANGED_FOOTER = 3;
        public static final int ADVERTISE = 4;
    }
```

And there where some other optimisation from the logics calculated from the count like getitemcounts. There is no effects from the previous functionality but its a better way to conclude them into the library.

**Comment by jjhesk** [comment]
hold on the merge. let me extend and make a new class

**Comment by jjhesk** [comment]
by the way, where do you host a gif?

**Pull request closed without merging**
