### PR TITLE
Migrate to AndroidX, upgrade libraries, general cleanup

### PR DESCRIPTION
**Pull request by vanshg**
As per https://github.com/cymcsg/UltimateRecyclerView/issues/496, this PR:

- Updates the library to use AndroidX

And in addition:
- Does some general clean up
- Update Gradle version
- Update SDK version to 28
- Update various library versions
- Update ultimaterecyclerview library version to 0.8.0 (since the API does technically change)
- Update sample app version
- Update README with new library version number

### CODE REVIEW

**Comment by vanshg** [comment]
Although it looks like an intimidating PR with many changes, most of them are just migrating import statements

**Comment by cymcsg** [comment]
Thanks @vanshg . Could you PR to dev branch instead of master branch? Then I will merge the dev branch into master.

**Comment by vanshg** [comment]
Sure thing @cymcsg

**Comment by vanshg** [comment]
@cymcsg I have resubmitted the PR with target branch set to `dev` https://github.com/cymcsg/UltimateRecyclerView/pull/498

**Pull request closed without merging**
